FROM python:3.12-slim-bookworm

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src
COPY data /app/data
COPY tests /app/tests
COPY utils /app/utils
COPY workers /app/workers
COPY main.py /app/main.py

EXPOSE 8080

CMD ["python", "main.py"]