FROM python:3.12-slim-bookworm

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/ /app/src/
COPY ./data/ /app/data/
COPY ./utils/ /app/utils/
COPY ./workers/ /app/workers/
COPY ./main.py /app/main.py

CMD ["uvicorn", "workers.subscriber:app", "--host", "0.0.0.0", "--port", "8080"]