name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11  
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run Pytest with HTML reports
        run: |
          mkdir -p tests/reports
          PYTHONPATH=. pytest tests/test_load_data.py --html=tests/reports/loader_tests.html
          PYTHONPATH=. pytest tests/test_gcp.py --html=tests/reports/cloud_storage_tests.html
          PYTHONPATH=. pytest tests/test_hyperparams_opt.py --html=tests/reports/trainning_tests.html
          PYTHONPATH=. pytest tests/test_monitoring_supervised_model.py --html=tests/reports/monitoring_supmodel_tests.html
          PYTHONPATH=. pytest tests/test_monitoring_unsupervised_model.py --html=tests/reports/monitoring_unsupmodel_tests.html